sudo: false

language: python

env:
  matrix:
   - TOXENV=py27
   - TOXENV=py33
   - TOXENV=py34
install:
  - pip install tox
script: tox
after_script:
  - if test "$TOXENV" = py34 ; then coveralls ; fi
  - if test "$TOXENV" = py34 ; echo $TOXENV ; fi
  - echo $TOXENV